### ISSUE TITLE
[KDE Plasma] Caffeine sometimes does not start on login

### ISSUE THREAD

**Issue by Tank-Missile** [caffeine-ng/caffeine-ng#20]
I added a delay in an attempt to workaround the issue since I assumed the cause was starting it before the panel started. Unfortunately, this didn't fix the issue. Attempting to start caffeine after login if it did not start does not work either. The only way I can get it to start at that point is to relogin.

**Comment by WhyNotHugo** [comment]
How are you trying to auto-start it?

Since it doesn't work later either, I'm getting an impression that it runs *before* KDE has started up, so the icons doesn't show up, but later copies refuse to start because of it.

**Comment by Tank-Missile** [comment]
I'm using Autostart from KDE's System Settings.

**Comment by wolfyrion** [comment]
I have sometimes  the same problem as well in order to start it again I have to do

caffeine kill
getting an error message like

/usr/lib/python3.7/site-packages/caffeine/main.py:59: PyGIWarning: AppIndicator3 was imported without specifying a version first. Use gi.require_version('AppIndicator3', '0.1') before import to ensure that the right version gets loaded.
  from gi.repository import AppIndicator3

and then start it again

**Comment by Tank-Missile** [comment]
caffeine kill does indeed allow caffeine to start, so at least I don't have to relogin anymore. I noticed that caffeine starts on login even when it's not added to Autostart, which I find quite odd.

**Comment by WhyNotHugo** [comment]
This repository has [moved to codeberg](https://github.com/caffeine-ng/caffeine-ng/issues/117).

Follow-up for this issue is at https://codeberg.org/WhyNotHugo/caffeine-ng/issues/20
